version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: querymq
    ports:
      - "5672:5672"
    networks:
      - rabbitmq
  server:
    build: "."
    image: pupymed/pubmed-crawler
    container_name: query-service
    ports:
      - "5001:5001"
    depends_on: [rabbitmq]
    working_dir: /usr/src/app
    volumes:
      - ./.log/:/usr/src/app/.log
    env_file:
      - rabbitmq-variables.env
    environment:
      - MODE=Service
    networks:
      - rabbitmq
  worker:
    build: "."
    image: pupymed/pubmed-crawler
    container_name: query-worker
    depends_on: [rabbitmq, server]
    working_dir: /usr/src/app
    volumes:
      - ./.log/:/usr/src/app/.log
      - ./.out/:/usr/src/app/.out
    env_file:
      - rabbitmq-variables.env
    environment:
      - MODE=Worker
    networks:
      - rabbitmq
networks:
  rabbitmq:
